logging.level.root=INFO

logging.level.org.apache.jena=INFO

logging.config=classpath:logback.xml

spring.servlet.multipart.max-file-size=32GB
spring.servlet.multipart.max-request-size=32GB
server.tomcat.max-swallow-size=32GB
server.tomcat.max-http-form-post-size=32GB